[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = [
  'pnpm install --frozen-lockfile',
  'cd apps/api && pnpm prisma generate'
]

[start]
cmd = 'cd apps/api && pnpm ts-node -r tsconfig-paths/register src/main.ts'
