[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = ['pnpm install --frozen-lockfile']

[phases.build]
cmds = ['pnpm nx build web --prod']

[start]
cmd = 'npx serve dist/apps/web -s -l $PORT'
# Force Railway to use Nixpacks
