[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = ['pnpm install --frozen-lockfile', 'pnpm add express -w']

[phases.build]
cmds = ['pnpm nx build web --prod']

[start]
cmd = 'node server.js'
# Force Railway to use Nixpacks
